# Generated by Django 4.1.7 on 2023-05-03 15:15

from django.db import migrations


def remove_orphan_tasks(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Task = apps.get_model("taskeditor", "Task")
    for task in Task.objects.filter(user=None):
        task.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('taskeditor', '0002_task_is_completed'),
    ]

    operations = [
        migrations.RunPython(remove_orphan_tasks),
    ]
