# Generated by Django 4.1.7 on 2023-05-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskeditor', '0005_group_task_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='name',
        ),
    ]
